

title: RubyLLM MCP
email: patrickgvice@gmail.com
description: >-
  A Ruby client for the Model Context Protocol (MCP) that seamlessly integrates with RubyLLM.
baseurl: "/"
url: "https://rubyllm-mcp.com"

theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Just the Docs settings

logo: /assets/images/rubyllm-mcp-logo-type.svg
favicon_ico: "/assets/images/favicon/favicon.ico"
favicon_png: "/assets/images/favicon/favicon-96x96.png"
favicon_svg: "/assets/images/favicon/favicon.svg"

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_external_links:
  - title: GitHub
    url: https://github.com/crmne/ruby_llm
    hide_icon: false

back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 <a href='https://patrickvice.com'>Patrick Vice</a>. Distributed under an <a href=\"https://github.com/patvice/ruby_llm-mcp/tree/main/LICENSE\">MIT license.</a>"

# Enable navigation
nav_enabled: true

# Make Anchor links show on hover
heading_anchors: true

# Color scheme
color_scheme: light

# Callouts
callouts:
  new:
    title: New
    color: green
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
