name: CICD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Ruby Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1.3', '3.2', '3.3', '3.4']

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.16

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Ruby dependencies
        run: |
          bundle install

      - name: Run specs
        run: bundle exec rake
        env:
          GITHUB_ACTIONS: "true"
