name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.1.3', '3.2', '3.3', '3.4']

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.16

      - name: Install dependencies for typescript-mcp && pagination-server
        run: |
          cd spec/fixtures/typescript-mcp
          bun install
          cd ../pagination-server
          bun install
          cd ../../..

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies for gem and fast-mcp
        run: |
          bundle install
          cd spec/fixtures/fast-mcp-ruby
          bundle install
          cd ../../..


      - name: Generate random ports
        id: portgen
        run: |
          echo "PORT1=$(( (RANDOM % 1000) + 3000 ))" >> $GITHUB_ENV
          echo "PORT2=$(( (RANDOM % 1000) + 4000 ))" >> $GITHUB_ENV
          echo "PORT3=$(( (RANDOM % 1000) + 5000 ))" >> $GITHUB_ENV

      - name: Run the test suite
        run: PORT1=$PORT1 PORT2=$PORT2 PORT3=$PORT3 bundle exec rake
        env:
          PORT1: ${{ env.PORT1 }}
          PORT2: ${{ env.PORT2 }}
          PORT3: ${{ env.PORT3 }}
